/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PayrollManagement;

import javax.swing.JOptionPane;
import java.sql.*;
import java.util.*;
import java.time.format.*;
import java.time.*;
import java.text.*;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author saikrishna
 */
public class AdministratorForm extends javax.swing.JFrame {

    /**
     * Creates new form AdministratorForm
     */
    private String Date;
    private employee emp = new employee();
    
    public AdministratorForm() {
        initComponents();
        this.jPaneldetails.setVisible(false);
        this.jPaneldelete.setVisible(false);
        LocalDate localDate = LocalDate.now();
        this.Date=DateTimeFormatter.ofPattern("dd/MM/yyy").format(localDate);
        this.jLabeldandt.setText(DateTimeFormatter.ofPattern("dd/MM/yyy").format(localDate));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttongroupsex = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPaneldetails = new javax.swing.JPanel();
        jTextFieldname = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldid = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFielddep = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaAdd = new javax.swing.JTextArea();
        jButtonreset = new javax.swing.JButton();
        Registerbtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldpass = new javax.swing.JTextField();
        rmale = new javax.swing.JRadioButton();
        rfemale = new javax.swing.JRadioButton();
        updatebtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldsalary = new javax.swing.JTextField();
        jButtonclose = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButtonAdde = new javax.swing.JButton();
        jButtonddelete = new javax.swing.JButton();
        jButtonupdate = new javax.swing.JButton();
        AdminLogout = new javax.swing.JButton();
        jLabeldandt = new javax.swing.JLabel();
        jPaneldelete = new javax.swing.JPanel();
        jButtondelete = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jTextFielddeleteid = new javax.swing.JTextField();
        jButtondclose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(192, 63, 63));
        jPanel1.setBorder(null);

        jPaneldetails.setBackground(new java.awt.Color(72, 84, 168));
        jPaneldetails.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Name-");

        jLabel2.setText("Id-");

        jLabel3.setText("Department");

        jLabel4.setText("Address");

        jTextAreaAdd.setColumns(20);
        jTextAreaAdd.setRows(5);
        jScrollPane1.setViewportView(jTextAreaAdd);

        jButtonreset.setText("reset");
        jButtonreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonresetActionPerformed(evt);
            }
        });

        Registerbtn.setText("Register");
        Registerbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterbtnActionPerformed(evt);
            }
        });

        jLabel5.setText("PassWord");

        rmale.setText("male");
        rmale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rmaleActionPerformed(evt);
            }
        });

        rfemale.setText("female");
        rfemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rfemaleActionPerformed(evt);
            }
        });

        updatebtn.setText("update");
        updatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebtnActionPerformed(evt);
            }
        });

        jLabel6.setText("sex");

        jLabel7.setText("Salary");

        jButtonclose.setText("close");
        jButtonclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtoncloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPaneldetailsLayout = new javax.swing.GroupLayout(jPaneldetails);
        jPaneldetails.setLayout(jPaneldetailsLayout);
        jPaneldetailsLayout.setHorizontalGroup(
            jPaneldetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneldetailsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPaneldetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPaneldetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(jLabel5)
                    .addComponent(jButtonreset, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPaneldetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPaneldetailsLayout.createSequentialGroup()
                        .addComponent(Registerbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(updatebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonclose, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextFieldpass)
                    .addComponent(jTextFieldname)
                    .addComponent(jTextFieldid)
                    .addComponent(jTextFielddep)
                    .addComponent(jScrollPane1)
                    .addComponent(jTextFieldsalary)
                    .addGroup(jPaneldetailsLayout.createSequentialGroup()
                        .addComponent(rmale)
                        .addGap(28, 28, 28)
                        .addComponent(rfemale)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPaneldetailsLayout.setVerticalGroup(
            jPaneldetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneldetailsLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPaneldetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPaneldetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPaneldetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFielddep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPaneldetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPaneldetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rmale)
                    .addComponent(rfemale)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPaneldetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldsalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPaneldetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPaneldetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonreset)
                    .addComponent(jButtonclose)
                    .addComponent(updatebtn)
                    .addComponent(Registerbtn))
                .addGap(64, 64, 64))
        );

        jPanel2.setBackground(new java.awt.Color(84, 98, 228));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButtonAdde.setText("Add Employee");
        jButtonAdde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddeActionPerformed(evt);
            }
        });

        jButtonddelete.setText("Delete Employee");
        jButtonddelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonddeleteActionPerformed(evt);
            }
        });

        jButtonupdate.setText("Update EmployeeDetails");
        jButtonupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonupdateActionPerformed(evt);
            }
        });

        AdminLogout.setText("LOGOUT");
        AdminLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonAdde, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jButtonddelete, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AdminLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAdde)
                    .addComponent(jButtonupdate)
                    .addComponent(jButtonddelete)
                    .addComponent(AdminLogout))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabeldandt.setText("Date");

        jPaneldelete.setBackground(new java.awt.Color(57, 115, 202));
        jPaneldelete.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButtondelete.setText("Delete");
        jButtondelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtondeleteActionPerformed(evt);
            }
        });

        jLabel8.setText("UserId");

        jButtondclose.setText("close");
        jButtondclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtondcloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPaneldeleteLayout = new javax.swing.GroupLayout(jPaneldelete);
        jPaneldelete.setLayout(jPaneldeleteLayout);
        jPaneldeleteLayout.setHorizontalGroup(
            jPaneldeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneldeleteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPaneldeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPaneldeleteLayout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFielddeleteid, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPaneldeleteLayout.createSequentialGroup()
                        .addComponent(jButtondelete, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(jButtondclose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(23, 23, 23))
        );
        jPaneldeleteLayout.setVerticalGroup(
            jPaneldeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPaneldeleteLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPaneldeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextFielddeleteid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPaneldeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtondelete)
                    .addComponent(jButtondclose))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPaneldetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPaneldelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabeldandt, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabeldandt, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPaneldetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPaneldelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AdminLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminLogoutActionPerformed
        // TODO add your handling code here:
        int dialogButton = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(this, "Do you want to \n Logout", "Logout Confirmation", dialogButton);
        if(dialogResult == 0) {
            this.dispose();
            new Login().setVisible(true);
        }

    }//GEN-LAST:event_AdminLogoutActionPerformed

    private void rmaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rmaleActionPerformed
        // TODO add your handling code here:
        this.emp.Sex="male";
        
    }//GEN-LAST:event_rmaleActionPerformed

    private void jButtonresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonresetActionPerformed
        // TODO add your handling code here:
        this.jTextFielddep.setText("");
        this.jTextFieldname.setText("");
        this.jTextFieldid.setText("");
        this.jTextAreaAdd.setText("");
        this.jTextFieldpass.setText("");
        this.jTextFieldsalary.setText("");
        this.rfemale.setSelected(false);
       
        //this.jTextFielddoj.setText("");
      
    }//GEN-LAST:event_jButtonresetActionPerformed

    private void jButtonupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonupdateActionPerformed
        // TODO add your handling code here:
        this.jPaneldetails.setVisible(true);
         this.jPaneldelete.setVisible(false);
        this.Registerbtn.setVisible(false);
        this.updatebtn.setVisible(true);
        
    }//GEN-LAST:event_jButtonupdateActionPerformed

    private void jButtonddeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonddeleteActionPerformed
        // TODO add your handling code here:
       this.jPaneldetails.setVisible(false);
       this.jPaneldelete.setVisible(true);
       this.jTextFielddeleteid.setText("");
    }//GEN-LAST:event_jButtonddeleteActionPerformed

    private void jButtonAddeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddeActionPerformed
        // TODO add your handling code here:
        this.jPaneldetails.setVisible(true);
         this.jPaneldelete.setVisible(false);
        this.Registerbtn.setVisible(true);
        //this.deletebtn.setVisible(false);
        this.updatebtn.setVisible(false);
    }//GEN-LAST:event_jButtonAddeActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        this.buttongroupsex.add(this.rmale);
        this.buttongroupsex.add(this.rfemale);
    }//GEN-LAST:event_formWindowOpened

    private void rfemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rfemaleActionPerformed
        // TODO add your handling code here:
        this.emp.Sex="female";
    }//GEN-LAST:event_rfemaleActionPerformed

    private void RegisterbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterbtnActionPerformed
        // TODO add your handling code here:
        try {
            Connection con=null;
            // Statement smt = null;
            String fields="UserId,name,PassWord,department,Salary,Address,Doj,Sex";
            PreparedStatement pst =null;
            ResultSet rs;
            String url= String.format("jdbc:sqlite:EmployeeData.sqlite");
            
            Class.forName("org.sqlite.JDBC");
            con = DriverManager.getConnection(url);
            String sql = String.format("INSERT INTO Data(%s) VALUES(?,?,?,?,?,?,?,?);",fields);
            pst = con.prepareStatement(sql);
            pst.setString(1, this.jTextFieldid.getText());
            pst.setString(2, this.jTextFieldname.getText());
            pst.setString(3, this.jTextFieldpass.getText());
            pst.setString(4, this.jTextFielddep.getText());
            pst.setDouble(5, Double.parseDouble(this.jTextFieldsalary.getText().trim()));
            pst.setString(6, this.jTextAreaAdd.getText());
            pst.setString(7, this.Date);
            pst.setString(8, this.emp.Sex);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Sucess fully registered");
            pst.close();
            con.close();
            
            
            
            
            
        } catch (SQLException | ClassNotFoundException ex) {
          System.out.println(ex.getMessage());
          JOptionPane.showMessageDialog(this, "enter valid Details");
        }
        
    }//GEN-LAST:event_RegisterbtnActionPerformed

    private void jButtondeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtondeleteActionPerformed
        // TODO add your handling code here:
        Connection con=null;
         PreparedStatement pst =null;
        try {
            
            // Statement smt = null;
            String fields="UserId,name,PassWord,department,Salary,Address,Doj,Sex";
            
            ResultSet rs;
            String url= String.format("jdbc:sqlite:EmployeeData.sqlite");
            
            Class.forName("org.sqlite.JDBC");
            con = DriverManager.getConnection(url);
            String sqlcheck = "UPDATE Data SET UserId=? WHERE UserId=?;";
            pst = con.prepareStatement(sqlcheck);
            pst.setString(1,this.jTextFieldid.getText());
            pst.setString(2,this.jTextFieldid.getText());
            pst.executeUpdate();
            pst.close();
            String sql = "DELETE FROM Data where UserId=?;";
            pst = con.prepareStatement(sql);
            pst.setString(1, this.jTextFielddeleteid.getText());
            pst.executeUpdate();
        
            JOptionPane.showMessageDialog(this, String.format("Sucess fully deleted id : %s",this.jTextFielddeleteid.getText()));
            
        } catch (SQLException | ClassNotFoundException ex) {
          System.out.println(ex.getMessage());
          JOptionPane.showMessageDialog(this, "enter valid Details");
        }
        try {
            pst.close();
        } catch (SQLException ex) {
            Logger.getLogger(AdministratorForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            con.close();
        } catch (SQLException ex) {
            Logger.getLogger(AdministratorForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_jButtondeleteActionPerformed

    private void updatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebtnActionPerformed
        // TODO add your handling code here:
         try {
            Connection con=null;
            // Statement smt = null;
            String fields="name=?,PassWord=?,department=?,Salary=?,Address=?,Sex=?";
            PreparedStatement pst =null;
            ResultSet rs;
            String url= String.format("jdbc:sqlite:EmployeeData.sqlite");
            
            Class.forName("org.sqlite.JDBC");
            con = DriverManager.getConnection(url);
            
            
            
            String sql = String.format("UPDATE Data SET %s WHERE UserId=?;",fields);
            pst = con.prepareStatement(sql);
            
            pst.setString(1, this.jTextFieldname.getText());
            pst.setString(2, this.jTextFieldpass.getText());
            pst.setString(3, this.jTextFielddep.getText());
            pst.setDouble(4, Double.parseDouble(this.jTextFieldsalary.getText().trim()));
            pst.setString(5, this.jTextAreaAdd.getText());
            pst.setString(6, this.emp.Sex);
            pst.setString(7,this.jTextFieldid.getText());
            pst.executeUpdate();
            
            JOptionPane.showMessageDialog(this, String.format("Sucess fully updated details of id : %s",this.jTextFieldid.getText()));
            pst.close();
            con.close(); 
            
        } catch (SQLException | ClassNotFoundException ex) {
          System.out.println(ex.getMessage());
          JOptionPane.showMessageDialog(this, "enter valid Details");
        }
    }//GEN-LAST:event_updatebtnActionPerformed

    private void jButtoncloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtoncloseActionPerformed
        // TODO add your handling code here:
        this.jPaneldetails.setVisible(false);
        this.jButtonresetActionPerformed(evt);
    }//GEN-LAST:event_jButtoncloseActionPerformed

    private void jButtondcloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtondcloseActionPerformed
        // TODO add your handling code here:
        this.jPaneldelete.setVisible(false);
    }//GEN-LAST:event_jButtondcloseActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(AdministratorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(AdministratorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(AdministratorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(AdministratorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new AdministratorForm().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AdminLogout;
    private javax.swing.JButton Registerbtn;
    private javax.swing.ButtonGroup buttongroupsex;
    private javax.swing.JButton jButtonAdde;
    private javax.swing.JButton jButtonclose;
    private javax.swing.JButton jButtondclose;
    private javax.swing.JButton jButtonddelete;
    private javax.swing.JButton jButtondelete;
    private javax.swing.JButton jButtonreset;
    private javax.swing.JButton jButtonupdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabeldandt;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPaneldelete;
    private javax.swing.JPanel jPaneldetails;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaAdd;
    private javax.swing.JTextField jTextFielddeleteid;
    private javax.swing.JTextField jTextFielddep;
    private javax.swing.JTextField jTextFieldid;
    private javax.swing.JTextField jTextFieldname;
    private javax.swing.JTextField jTextFieldpass;
    private javax.swing.JTextField jTextFieldsalary;
    private javax.swing.JRadioButton rfemale;
    private javax.swing.JRadioButton rmale;
    private javax.swing.JButton updatebtn;
    // End of variables declaration//GEN-END:variables
}
