/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PayrollManagement;

import java.sql.*;
import java.util.*;
import java.time.format.*;
import java.time.*;
import java.text.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */




public class EmployeeForm extends javax.swing.JFrame {

    /**
     * Creates new form EmployeeForm
     */
    private int rowId;
    
    private employee emp =new employee();
    
    private employee Getdetails(int rowno){
            employee e = new employee();
        
        try {
            Connection con=null;
            // Statement smt = null;
            PreparedStatement pst =null;
            ResultSet rs;
            String url= String.format("jdbc:sqlite:EmployeeData.sqlite");
            
            Class.forName("org.sqlite.JDBC");
            con = DriverManager.getConnection(url);
            String sql = " SELECT rowid,* from Data "+ String.format(" WHERE rowid=%d ;",rowno);
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            e.name=rs.getString("name");
            e.UserId=rs.getString("UserId");
            e.Address=rs.getString("Address");
            e.department=rs.getString("department");
            e.PassWord=rs.getString("PassWord");
            e.Salary = rs.getDouble("Salary");
            e.TA=rs.getDouble("TA");
            e.DA=rs.getDouble("DA");
            e.Deduction=rs.getDouble("Deduction");
            e.PF=rs.getDouble("PF");
            e.Attendence=rs.getInt("Attendence");
            e.Leaves=rs.getInt("Leaves");
            this.jLabelWelcome.setText(String.format("WELCOME USER : %s", e.name));
            
            rs.close();
            pst.close();
            con.close();
            
            
            
            
            
        } catch (SQLException | ClassNotFoundException ex) {
          System.out.println(ex.getMessage());
        }
       
        
        return e;
    }
    
    public EmployeeForm(int Id) {
        
        initComponents();
        this.rowId=Id;
        this.jPanelcp.setVisible(false);
        this.jPaneldetails.setVisible(false);
        this.jPanelleave.setVisible(false);
        this.emp=this.Getdetails(Id);
        
        LocalDate localDate = LocalDate.now();
        this.jLabeldandt.setText(DateTimeFormatter.ofPattern("dd/MM/yyy").format(localDate));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Attenbtn = new javax.swing.JButton();
        salarybtn = new javax.swing.JButton();
        viewleavesbtn = new javax.swing.JButton();
        deductionbtn = new javax.swing.JButton();
        Appleavebtn = new javax.swing.JButton();
        passwdbtn = new javax.swing.JButton();
        Logout = new javax.swing.JButton();
        jLabeldandt = new javax.swing.JLabel();
        jPanelcp = new javax.swing.JPanel();
        jTextFieldop = new javax.swing.JTextField();
        jTextFieldnp = new javax.swing.JTextField();
        jButtoncpok = new javax.swing.JButton();
        jButtoncpclose = new javax.swing.JButton();
        jPaneldetails = new javax.swing.JPanel();
        jLabeldetails = new javax.swing.JLabel();
        jButtontdetailscl = new javax.swing.JButton();
        jPanelleave = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldlv = new javax.swing.JTextField();
        jButtonlok = new javax.swing.JButton();
        jButtonlclose = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabelWelcome = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(137, 45, 45));
        jPanel1.setBorder(null);

        Attenbtn.setText("Give Attendence");
        Attenbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AttenbtnActionPerformed(evt);
            }
        });

        salarybtn.setText("View Salary");
        salarybtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salarybtnActionPerformed(evt);
            }
        });

        viewleavesbtn.setText("view Leave details");
        viewleavesbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewleavesbtnActionPerformed(evt);
            }
        });

        deductionbtn.setText("view deduction details");
        deductionbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deductionbtnActionPerformed(evt);
            }
        });

        Appleavebtn.setText("Apply for leave");
        Appleavebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AppleavebtnActionPerformed(evt);
            }
        });

        passwdbtn.setText("change password");
        passwdbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwdbtnActionPerformed(evt);
            }
        });

        Logout.setText("Logout");
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });

        jLabeldandt.setBackground(new java.awt.Color(40, 91, 203));
        jLabeldandt.setText("date and time");

        jPanelcp.setBackground(new java.awt.Color(32, 4, 208));
        jPanelcp.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTextFieldop.setText("OldPassWord");
        jTextFieldop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldopMouseClicked(evt);
            }
        });

        jTextFieldnp.setText("NewPassWord");
        jTextFieldnp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldnpMouseClicked(evt);
            }
        });
        jTextFieldnp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldnpActionPerformed(evt);
            }
        });

        jButtoncpok.setText("ok");
        jButtoncpok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtoncpokActionPerformed(evt);
            }
        });

        jButtoncpclose.setText("close");
        jButtoncpclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtoncpcloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelcpLayout = new javax.swing.GroupLayout(jPanelcp);
        jPanelcp.setLayout(jPanelcpLayout);
        jPanelcpLayout.setHorizontalGroup(
            jPanelcpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelcpLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanelcpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelcpLayout.createSequentialGroup()
                        .addComponent(jButtoncpok, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtoncpclose, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextFieldop, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldnp, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanelcpLayout.setVerticalGroup(
            jPanelcpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelcpLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextFieldop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldnp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelcpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtoncpok)
                    .addComponent(jButtoncpclose))
                .addContainerGap())
        );

        jPaneldetails.setBackground(new java.awt.Color(127, 143, 150));
        jPaneldetails.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabeldetails.setText("jLabel1");

        jButtontdetailscl.setText("close");
        jButtontdetailscl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtontdetailsclActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPaneldetailsLayout = new javax.swing.GroupLayout(jPaneldetails);
        jPaneldetails.setLayout(jPaneldetailsLayout);
        jPaneldetailsLayout.setHorizontalGroup(
            jPaneldetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneldetailsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabeldetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPaneldetailsLayout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addComponent(jButtontdetailscl, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPaneldetailsLayout.setVerticalGroup(
            jPaneldetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneldetailsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabeldetails, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jButtontdetailscl)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelleave.setBackground(new java.awt.Color(54, 40, 221));
        jPanelleave.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("Enter leaves");

        jButtonlok.setText("ok");
        jButtonlok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonlokActionPerformed(evt);
            }
        });

        jButtonlclose.setText("close");
        jButtonlclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonlcloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelleaveLayout = new javax.swing.GroupLayout(jPanelleave);
        jPanelleave.setLayout(jPanelleaveLayout);
        jPanelleaveLayout.setHorizontalGroup(
            jPanelleaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelleaveLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelleaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jButtonlok, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelleaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldlv)
                    .addGroup(jPanelleaveLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonlclose, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanelleaveLayout.setVerticalGroup(
            jPanelleaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelleaveLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelleaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldlv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelleaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonlok)
                    .addComponent(jButtonlclose))
                .addGap(28, 28, 28))
        );

        jPanel4.setBackground(new java.awt.Color(95, 78, 78));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelWelcome.setBackground(new java.awt.Color(52, 35, 35));
        jLabelWelcome.setText("jLabel3");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(152, 152, 152))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelWelcome, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Attenbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(salarybtn, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(viewleavesbtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                                .addComponent(Appleavebtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(Logout, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deductionbtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(passwdbtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPaneldetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(34, 34, 34))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanelcp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanelleave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(6, 6, 6))))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jLabeldandt, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabeldandt))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelcp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Attenbtn)
                        .addGap(12, 12, 12)
                        .addComponent(salarybtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(deductionbtn)
                        .addGap(18, 18, 18)
                        .addComponent(passwdbtn))
                    .addComponent(jPanelleave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Appleavebtn)
                        .addGap(18, 18, 18)
                        .addComponent(viewleavesbtn)
                        .addGap(217, 217, 217)
                        .addComponent(Logout))
                    .addComponent(jPaneldetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AttenbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AttenbtnActionPerformed
        // TODO add your handling code here:
        int at =emp.Attendence;
        at++;
         Connection con = null;
            // Statement smt = null;
            String fields="Attendence=?";
            PreparedStatement pst = null ;
            ResultSet rs;
        try {
           
            String url= String.format("jdbc:sqlite:EmployeeData.sqlite");
            
            Class.forName("org.sqlite.JDBC");
            con = DriverManager.getConnection(url);
            
            
            
            String sql = String.format("UPDATE Data SET %s WHERE UserId=?;",fields);
            pst = con.prepareStatement(sql);
            pst.setInt(1, at);
            pst.setString(2, emp.UserId);
            pst.executeUpdate();
            
            
            JOptionPane.showMessageDialog(this,"Sucessfulyy given Attendence");
            
            
        } catch (SQLException | ClassNotFoundException ex) {
          System.out.println(ex.getMessage());
        }
       
        
        
        try {
            pst.close();
        } catch (SQLException ex) {
            Logger.getLogger(EmployeeForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        try { 
            con.close();
        } catch (SQLException ex) {
            Logger.getLogger(EmployeeForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.Attenbtn.setEnabled(false);
        
    }//GEN-LAST:event_AttenbtnActionPerformed

    private void AppleavebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AppleavebtnActionPerformed
        // TODO add your handling code here:
        this.jPanelleave.setVisible(true);
        
    }//GEN-LAST:event_AppleavebtnActionPerformed

    private void viewleavesbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewleavesbtnActionPerformed
        // TODO add your handling code here:
        String details=String.format("No of Leaves Taken : \t %d \n No of Leaves Remaining :\t %d\n", emp.Leaves,15-emp.Leaves);
        this.jPaneldetails.setVisible(true);
        this.jLabeldetails.setText(details);
        
        
    }//GEN-LAST:event_viewleavesbtnActionPerformed

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        // TODO add your handling code here:
         int input;
        input = JOptionPane.showConfirmDialog(this,
                "Do you want to LOGOUT", "LOG OUT",
                JOptionPane.OK_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE);
        if(input==0){
        this.dispose();
        new Login().setVisible(true);
        }
        
    }//GEN-LAST:event_LogoutActionPerformed
    public double Getsalary(){
        double Salary=0;
        
        Salary = (emp.TA+emp.DA+emp.PF)*emp.Salary;
        
        
        return Salary;
    }
    private void salarybtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salarybtnActionPerformed
        // TODO add your handling code here:
        this.jPaneldetails.setVisible(true);
        this.jLabeldetails.setText(String.format(" salary: \t %f", this.Getsalary()));
        
    }//GEN-LAST:event_salarybtnActionPerformed

    private void deductionbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deductionbtnActionPerformed
        // TODO add your handling code here:
        this.jPaneldetails.setVisible(true);
        String deductions = String.format("Deductions are : \t %f\n",emp.Deduction);
        this.jLabeldetails.setText(deductions);
    }//GEN-LAST:event_deductionbtnActionPerformed

    private void jTextFieldnpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldnpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldnpActionPerformed

    private void passwdbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwdbtnActionPerformed
        // TODO add your handling code here:
        this.jPanelcp.setVisible(true);
        this.jTextFieldnp.setText("New PassWord");
        this.jTextFieldop.setText("Old PassWord");
        
        
    }//GEN-LAST:event_passwdbtnActionPerformed

    private void jTextFieldopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldopMouseClicked
        // TODO add your handling code here:
        this.jTextFieldop.setText("");
    }//GEN-LAST:event_jTextFieldopMouseClicked

    private void jTextFieldnpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldnpMouseClicked
        // TODO add your handling code here:
        this.jTextFieldnp.setText("");
    }//GEN-LAST:event_jTextFieldnpMouseClicked

    private void jButtontdetailsclActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtontdetailsclActionPerformed
        // TODO add your handling code here:
        this.jLabeldetails.setText("");
        this.jPaneldetails.setVisible(false);
    }//GEN-LAST:event_jButtontdetailsclActionPerformed

    private void jButtoncpokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtoncpokActionPerformed
        // TODO add your handling code here:
      String np=  this.jTextFieldnp.getText();
      String op= this.jTextFieldop.getText();
      if(op.equals(emp.PassWord)){
          
    
               
            emp.PassWord=np;
            Connection con=null;
            // Statement smt = null;
            String fields="PassWord=?";
            PreparedStatement pst =null;
            ResultSet rs;

            try {

                String url= String.format("jdbc:sqlite:EmployeeData.sqlite");

                Class.forName("org.sqlite.JDBC");
                con = DriverManager.getConnection(url);



                String sql = String.format("UPDATE Data SET %s WHERE UserId=?;",fields);
                pst = con.prepareStatement(sql);
                pst.setString(1,np);
                pst.setString(2, emp.UserId);
                pst.executeUpdate();


                JOptionPane.showMessageDialog(this, "Sucessfully updated Password");
               

            } catch (SQLException | ClassNotFoundException ex) {
                System.out.println(ex.getMessage());
                JOptionPane.showMessageDialog(this, "enter valid Details");
            }
          try {
              pst.close();
          } catch (SQLException ex) {
              Logger.getLogger(EmployeeForm.class.getName()).log(Level.SEVERE, null, ex);
          }
          try {
              con.close();
          } catch (SQLException ex) {
              Logger.getLogger(EmployeeForm.class.getName()).log(Level.SEVERE, null, ex);
          }
               
               
               
               
         
            
          
          
          
      }
      else{
          JOptionPane.showMessageDialog(this, "Please enter your old \n Password correctly");
      }
    }//GEN-LAST:event_jButtoncpokActionPerformed

    private void jButtoncpcloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtoncpcloseActionPerformed
        // TODO add your handling code here:
        this.jPanelcp.setVisible(false);
        this.jTextFieldnp.setText("");
        this.jTextFieldop.setText("");
    }//GEN-LAST:event_jButtoncpcloseActionPerformed

    private void jButtonlokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonlokActionPerformed
        // TODO add your handling code here:
        int lv =Integer.parseInt(this.jTextFieldlv.getText().trim());
        int tlv= emp.Leaves;
        if(tlv+lv < emp.MaxLeaves){
             Connection con=null;
            // Statement smt = null;
            String fields="Leaves=?";
            PreparedStatement pst =null;
            ResultSet rs;
             try {
            
            String url= String.format("jdbc:sqlite:EmployeeData.sqlite");
            
            Class.forName("org.sqlite.JDBC");
            con = DriverManager.getConnection(url);
            
            
            
            String sql = String.format("UPDATE Data SET %s WHERE UserId=?;",fields);
            pst = con.prepareStatement(sql);
            pst.setInt(1, lv+tlv);
            pst.setString(2, emp.UserId);
            pst.executeUpdate();
            
            
            JOptionPane.showMessageDialog(this,"Sucessfulyy granted your leave");
            
            
        } catch (SQLException | ClassNotFoundException ex) {
          System.out.println(ex.getMessage());
        }
            try {
                pst.close();
            } catch (SQLException ex) {
                Logger.getLogger(EmployeeForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            try { 
                con.close();
            } catch (SQLException ex) {
                Logger.getLogger(EmployeeForm.class.getName()).log(Level.SEVERE, null, ex);
            }
    }
        else{
            JOptionPane.showMessageDialog(this, "Leaves limit exceeded");
        }
    }//GEN-LAST:event_jButtonlokActionPerformed

    private void jButtonlcloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonlcloseActionPerformed
        // TODO add your handling code here:
        this.jPanelleave.setVisible(false);
    }//GEN-LAST:event_jButtonlcloseActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(EmployeeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(EmployeeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(EmployeeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(EmployeeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new EmployeeForm().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Appleavebtn;
    private javax.swing.JButton Attenbtn;
    private javax.swing.JButton Logout;
    private javax.swing.JButton deductionbtn;
    private javax.swing.JButton jButtoncpclose;
    private javax.swing.JButton jButtoncpok;
    private javax.swing.JButton jButtonlclose;
    private javax.swing.JButton jButtonlok;
    private javax.swing.JButton jButtontdetailscl;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelWelcome;
    private javax.swing.JLabel jLabeldandt;
    private javax.swing.JLabel jLabeldetails;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanelcp;
    private javax.swing.JPanel jPaneldetails;
    private javax.swing.JPanel jPanelleave;
    private javax.swing.JTextField jTextFieldlv;
    private javax.swing.JTextField jTextFieldnp;
    private javax.swing.JTextField jTextFieldop;
    private javax.swing.JButton passwdbtn;
    private javax.swing.JButton salarybtn;
    private javax.swing.JButton viewleavesbtn;
    // End of variables declaration//GEN-END:variables
}
