/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PayrollManagement;


import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonlogin = new javax.swing.JButton();
        jButtonReset = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldUsern = new javax.swing.JTextField();
        jPasswordFieldPas = new javax.swing.JPasswordField();
        jComboBoxType = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(214, 118, 121));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonlogin.setForeground(new java.awt.Color(24, 27, 25));
        jButtonlogin.setText("Login");
        jButtonlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonloginActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, 210, 30));

        jButtonReset.setForeground(new java.awt.Color(244, 11, 14));
        jButtonReset.setText("Reset");
        jButtonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 320, 220, -1));

        jLabel1.setText("Username");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 92, -1, 30));

        jLabel4.setText("Login as");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 204, 90, -1));

        jLabel2.setText("Password");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 132, 80, 40));

        jTextFieldUsern.setText("Username");
        jTextFieldUsern.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldUsernMouseClicked(evt);
            }
        });
        jTextFieldUsern.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUsernActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldUsern, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 92, 150, -1));

        jPasswordFieldPas.setText("PassWord");
        jPasswordFieldPas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPasswordFieldPasMouseClicked(evt);
            }
        });
        jPasswordFieldPas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldPasActionPerformed(evt);
            }
        });
        jPanel1.add(jPasswordFieldPas, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 150, -1));

        jComboBoxType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Employee", "Manager", "Administrator" }));
        jComboBoxType.setToolTipText("Employee\nManager\nAdministrator");
        jComboBoxType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTypeActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxType, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 150, -1));

        jPanel2.setBackground(new java.awt.Color(187, 15, 15));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setBackground(new java.awt.Color(119, 86, 86));
        jLabel6.setFont(new java.awt.Font("Noto Sans", 3, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(77, 97, 240));
        jLabel6.setText("                   LOGIN INTO  PAYROLL MANAGEMENT SYSTEM");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 51));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 2, 622, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PayrollManagement/login.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 80, 170, 130));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldUsernActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUsernActionPerformed
        // TODO add your handling code here:
        
      
    }//GEN-LAST:event_jTextFieldUsernActionPerformed

    
    private int ValidateLogin(String usr,String pass,String option){
        try{
            Connection con=null;
           // Statement smt = null;
            PreparedStatement pst =null;
            ResultSet rs;
            String url= String.format("jdbc:sqlite:%sData.sqlite", option);
            
            Class.forName("org.sqlite.JDBC");
            con = DriverManager.getConnection(url);
            String sql = " SELECT rowid,* from Data "+" WHERE UserId=? ;";
            pst = con.prepareStatement(sql);
            pst.setString(1, usr);
            rs = pst.executeQuery();
            if(rs.getString("PassWord").equals(pass)){
                return rs.getInt("rowid");
            }
            
           rs.close();
           pst.close();
           con.close();
            
            
        } catch (ClassNotFoundException | SQLException ex) {
            System.out.println(ex.getMessage());
        }
        
        return -1;
        
    }
    private void jButtonloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonloginActionPerformed
                String usr,pass,option;
                usr = this.jTextFieldUsern.getText();
                pass = this.jPasswordFieldPas.getText();
                option = (String) this .jComboBoxType.getSelectedItem();
                int row=ValidateLogin(usr,pass,option);
                if(row!=-1){
                    switch(option){
                        case "Employee":
                            //System.out.println(row);
                                EmployeeForm form =new EmployeeForm(row);
                                form.setVisible(true);
                                this.dispose();
                                break;
                        case "Administrator":
                                new AdministratorForm().setVisible(true);
                                this.dispose();
                                break;
                          
                    }
                    
                }
                else{
                    JOptionPane.showMessageDialog(this, "Please enter valid Details");
                }
                
                
       
    }//GEN-LAST:event_jButtonloginActionPerformed

    private void jButtonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetActionPerformed
        // TODO add your handling code here:
        this.jTextFieldUsern.setText("");
        this.jPasswordFieldPas.setText("");
    }//GEN-LAST:event_jButtonResetActionPerformed

    private void jComboBoxTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTypeActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jComboBoxTypeActionPerformed
    
   
    
    
    private void jPasswordFieldPasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldPasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldPasActionPerformed

    private void jTextFieldUsernMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldUsernMouseClicked
        // TODO add your handling code here:
        this.jTextFieldUsern.setText("");
    }//GEN-LAST:event_jTextFieldUsernMouseClicked

    private void jPasswordFieldPasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordFieldPasMouseClicked
        // TODO add your handling code here:
        this.jPasswordFieldPas.setText("");
    }//GEN-LAST:event_jPasswordFieldPasMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               Login lgpg= new Login();
               lgpg.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonReset;
    private javax.swing.JButton jButtonlogin;
    private javax.swing.JComboBox jComboBoxType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordFieldPas;
    private javax.swing.JTextField jTextFieldUsern;
    // End of variables declaration//GEN-END:variables
}
